### PR TITLE
Replace OpenTracing with OpenTelemetry

### PR DESCRIPTION
**Pull request by indrekj**
View by commit.

### CODE REVIEW

**Review by sviik — APPROVED** [review]

**Review by urmastalimaa — COMMENTED** [review]
Did a very brief review. It seems that the span-building could be captured a bit more (perhaps in delivery.rb), currently it is quite spread across all the producer and consumer code.

**Comment by indrekj** [comment]
@urmastalimaa simplified the consumer part https://github.com/salemove/freddy/compare/ec739373b3a640467bfe8a0c846dd4f60a89054c..dbb1c411d2fea5273c328701d64dc2c17a3c7933

**Comment by urmastalimaa** [comment]
Can you do the producer part as well? There maybe isn't a suitable class for it, but could capture nonetheless.

**Comment by indrekj** [comment]
> Can you do the producer part as well? There maybe isn't a suitable class for it, but could capture nonetheless.

https://github.com/salemove/freddy/compare/dbb1c411d2fea5273c328701d64dc2c17a3c7933..ab029fddecb26085c18c745a55a9758cb046756b a bit better

**Pull request merged**
