### PR TITLE
Do not report recipient timeouts to Airbrake

### PR DESCRIPTION
**Pull request by willmore**
Failure to receive a response is not something that should generally be
logged in Aibrake. Timeouts are better suited for stats and logging.

### CODE REVIEW

**Comment by willmore** [comment]
Putting PR "On Hold" - found some more items to address w.r.t. suppressing timeouts.

**Comment by willmore** [comment]
Ready for review.

**Comment by indrekj** [comment]
Released as version `0.6.0`

**Comment by willmore** [comment]
>Released as version 0.6.0

Thanks @indrekj

**Pull request merged**
